In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("telco.csv")

In [4]:
df.shape

(3677, 50)

In [5]:
df.head()

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,...,20.0,0.00,59.65,3.0,Churned,Yes,91.0,5433.0,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,...,0.0,390.80,1024.10,3.0,Churned,Yes,69.0,5302.0,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,...,0.0,203.94,1910.88,2.0,Churned,Yes,81.0,3179.0,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,...,0.0,494.00,2995.07,2.0,Churned,Yes,88.0,5337.0,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,...,0.0,234.21,3102.36,2.0,Churned,Yes,67.0,2793.0,Price,Extra data charges

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3677 entries, 0 to 3676
Data columns (total 50 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        3677 non-null   object
 1   Gender                             3677 non-null   object
 2   Age                                3677 non-null   int64
 3   Under 30                           3677 non-null   object
 4   Senior Citizen                     3677 non-null   object
 5   Married                            3677 non-null   object
 6   Dependents                         3677 non-null   object
 7   Number of Dependents               3677 non-null   int64
 8   Country                            3677 non-null   object
 9   State                              3677 non-null   object
 10  City                               3677 non-null   object
 11  Zip Code                           3677 non-null   int64
 12  Latitude                           3677 non-null   float64
 13  Longitude                          3677 non-null   float64
 14  Population                         3677 non-null   int64
 15  Quarter                            3677 non-null   object
 16  Referred a Friend                  3677 non-null   object
 17  Number of Referrals                3677 non-null   int64
 18  Tenure in Months                   3677 non-null   int64
 19  Offer                              1607 non-null   object
 20  Phone Service                      3677 non-null   object
 21  Avg Monthly Long Distance Charges  3677 non-null   float64
 22  Multiple Lines                     3677 non-null   object
 23  Internet Service                   3677 non-null   object
 24  Internet Type                      3176 non-null   object
 25  Avg Monthly GB Download            3677 non-null   int64
 26  Online Security                    3677 non-null   object
 27  Online Backup                      3677 non-null   object
 28  Device Protection Plan             3677 non-null   object
 29  Premium Tech Support               3677 non-null   object
 30  Streaming TV                       3677 non-null   object
 31  Streaming Movies                   3677 non-null   object
 32  Streaming Music                    3677 non-null   object
 33  Unlimited Data                     3677 non-null   object
 34  Contract                           3677 non-null   object
 35  Paperless Billing                  3677 non-null   object
 36  Payment Method                     3677 non-null   object
 37  Monthly Charge                     3676 non-null   float64
 38  Total Charges                      3676 non-null   float64
 39  Total Refunds                      3676 non-null   float64
 40  Total Extra Data Charges           3676 non-null   float64
 41  Total Long Distance Charges        3676 non-null   float64
 42  Total Revenue                      3676 non-null   float64
 43  Satisfaction Score                 3676 non-null   float64
 44  Customer Status                    3676 non-null   object
 45  Churn Label                        3676 non-null   object
 46  Churn Score                        3676 non-null   float64
 47  CLTV                               3676 non-null   float64
 48  Churn Category                     1869 non-null   object
 49  Churn Reason                       1869 non-null   object
dtypes: float64(12), int64(7), object(31)
memory usage: 1.4+ MB

In [8]:
df.describe(include = "all")

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
count,3677,3677,3677.000000,3677,3677,3677,3677,3677.000000,3677,3677,...,3676.000000,3676.000000,3676.000000,3676.000000,3676,3676,3676.000000,3676.000000,1869,1869
unique,3677,2,NaN,2,2,2,2,NaN,1,1,...,NaN,NaN,NaN,NaN,3,2,NaN,NaN,5,20
top,8779-QRDMV,Male,NaN,No,No,No,No,NaN,United States,California,...,NaN,NaN,NaN,NaN,Churned,Yes,NaN,NaN,Competitor,Competitor had better devices
freq,1,1864,NaN,3100,2535,2033,3269,NaN,3677,3677,...,NaN,NaN,NaN,NaN,1869,1869,NaN,NaN,841,313
mean,NaN,NaN,51.358172,NaN,NaN,NaN,NaN,0.226271,NaN,NaN,...,7.200762,662.520862,2836.551681,2.731230,NaN,NaN,66.147443,4323.385745,NaN,NaN
std,NaN,NaN,18.114940,NaN,NaN,NaN,NaN,0.729031,NaN,NaN,...,25.493741,814.130877,2840.993420,1.286291,NaN,NaN,21.221950,1195.513277,NaN,NaN
min,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,...,0.000000,0.000000,21.610000,1.000000,NaN,NaN,5.000000,2003.000000,NaN,NaN
25%,NaN,NaN,36.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,...,0.000000,46.032500,422.357500,1.000000,NaN,NaN,51.000000,3349.750000,NaN,NaN
50%,NaN,NaN,52.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,...,0.000000,294.700000,1790.585000,3.000000,NaN,NaN,71.000000,4455.000000,NaN,NaN
75%,NaN,NaN,68.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,...,0.000000,1016.975000,4575.437500,4.000000,NaN,NaN,83.000000,5327.250000,NaN,NaN
max,NaN,NaN,80.000000,NaN,NaN,NaN,NaN,8.000000,NaN,NaN,...,150.000000,3564.000000,11795.780000,5.000000,NaN,NaN,96.000000,6500.000000,NaN,NaN

In [9]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

In [10]:
df.columns

Index(['customer_id', 'gender', 'age', 'under_30', 'senior_citizen', 'married',
       'dependents', 'number_of_dependents', 'country', 'state', 'city',
       'zip_code', 'latitude', 'longitude', 'population', 'quarter',
       'referred_a_friend', 'number_of_referrals', 'tenure_in_months', 'offer',
       'phone_service', 'avg_monthly_long_distance_charges', 'multiple_lines',
       'internet_service', 'internet_type', 'avg_monthly_gb_download',
       'online_security', 'online_backup', 'device_protection_plan',
       'premium_tech_support', 'streaming_tv', 'streaming_movies',
       'streaming_music', 'unlimited_data', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charge', 'total_charges', 'total_refunds',
       'total_extra_data_charges', 'total_long_distance_charges',
       'total_revenue', 'satisfaction_score', 'customer_status', 'churn_label',
       'churn_score', 'cltv', 'churn_category', 'churn_reason'],
      dtype='object')

In [11]:
df.nunique()

customer_id                          3677
gender                                  2
age                                    62
under_30                                2
senior_citizen                          2
married                                 2
dependents                              2
number_of_dependents                    9
country                                 1
state                                   1
city                                 1099
zip_code                             1616
latitude                             1616
longitude                            1615
population                           1560
quarter                                 1
referred_a_friend                       2
number_of_referrals                    12
tenure_in_months                       72
offer                                   5
phone_service                           2
avg_monthly_long_distance_charges    2423
multiple_lines                          2
internet_service                        2
internet_type                           3
avg_monthly_gb_download                50
online_security                         2
online_backup                           2
device_protection_plan                  2
premium_tech_support                    2
streaming_tv                            2
streaming_movies                        2
streaming_music                         2
unlimited_data                          2
contract                                3
paperless_billing                       2
payment_method                          4
monthly_charge                       1297
total_charges                        3464
total_refunds                         263
total_extra_data_charges               16
total_long_distance_charges          3249
total_revenue                        3648
satisfaction_score                      5
customer_status                         3
churn_label                             2
churn_score                            81
cltv                                 2454
churn_category                          5
churn_reason                           20
dtype: int64

In [12]:
df = df.drop(columns = ["country","state", "quarter"])

In [13]:
df.columns

Index(['customer_id', 'gender', 'age', 'under_30', 'senior_citizen', 'married',
       'dependents', 'number_of_dependents', 'city', 'zip_code', 'latitude',
       'longitude', 'population', 'referred_a_friend', 'number_of_referrals',
       'tenure_in_months', 'offer', 'phone_service',
       'avg_monthly_long_distance_charges', 'multiple_lines',
       'internet_service', 'internet_type', 'avg_monthly_gb_download',
       'online_security', 'online_backup', 'device_protection_plan',
       'premium_tech_support', 'streaming_tv', 'streaming_movies',
       'streaming_music', 'unlimited_data', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charge', 'total_charges', 'total_refunds',
       'total_extra_data_charges', 'total_long_distance_charges',
       'total_revenue', 'satisfaction_score', 'customer_status', 'churn_label',
       'churn_score', 'cltv', 'churn_category', 'churn_reason'],
      dtype='object')

In [14]:
df.isnull().sum()

customer_id                             0
gender                                  0
age                                     0
under_30                                0
senior_citizen                          0
married                                 0
dependents                              0
number_of_dependents                    0
city                                    0
zip_code                                0
latitude                                0
longitude                               0
population                              0
referred_a_friend                       0
number_of_referrals                     0
tenure_in_months                        0
offer                                2070
phone_service                           0
avg_monthly_long_distance_charges       0
multiple_lines                          0
internet_service                        0
internet_type                         501
avg_monthly_gb_download                 0
online_security                         0
online_backup                           0
device_protection_plan                  0
premium_tech_support                    0
streaming_tv                            0
streaming_movies                        0
streaming_music                         0
unlimited_data                          0
contract                                0
paperless_billing                       0
payment_method                          0
monthly_charge                          1
total_charges                           1
total_refunds                           1
total_extra_data_charges                1
total_long_distance_charges             1
total_revenue                           1
satisfaction_score                      1
customer_status                         1
churn_label                             1
churn_score                             1
cltv                                    1
churn_category                       1808
churn_reason                         1808
dtype: int64

In [50]:
df["offer"] = df["offer"].fillna("No Offer")
df["internet_type"] = df["internet_type"].fillna("No Internet")
df["churn_reason"] = df["churn_reason"].fillna("Not Churned")
df["churn_category"] = df["churn_category"].fillna("Not Churned")

In [18]:
df.isnull().sum()

customer_id                          0
gender                               0
age                                  0
under_30                             0
senior_citizen                       0
married                              0
dependents                           0
number_of_dependents                 0
city                                 0
zip_code                             0
latitude                             0
longitude                            0
population                           0
referred_a_friend                    0
number_of_referrals                  0
tenure_in_months                     0
offer                                0
phone_service                        0
avg_monthly_long_distance_charges    0
multiple_lines                       0
internet_service                     0
internet_type                        0
avg_monthly_gb_download              0
online_security                      0
online_backup                        0
device_protection_plan               0
premium_tech_support                 0
streaming_tv                         0
streaming_movies                     0
streaming_music                      0
unlimited_data                       0
contract                             0
paperless_billing                    0
payment_method                       0
monthly_charge                       1
total_charges                        1
total_refunds                        1
total_extra_data_charges             1
total_long_distance_charges          1
total_revenue                        1
satisfaction_score                   1
customer_status                      1
churn_label                          1
churn_score                          1
cltv                                 1
churn_category                       0
churn_reason                         0
dtype: int64

In [20]:
df = df.dropna()

In [21]:
df.isnull().sum()

customer_id                          0
gender                               0
age                                  0
under_30                             0
senior_citizen                       0
married                              0
dependents                           0
number_of_dependents                 0
city                                 0
zip_code                             0
latitude                             0
longitude                            0
population                           0
referred_a_friend                    0
number_of_referrals                  0
tenure_in_months                     0
offer                                0
phone_service                        0
avg_monthly_long_distance_charges    0
multiple_lines                       0
internet_service                     0
internet_type                        0
avg_monthly_gb_download              0
online_security                      0
online_backup                        0
device_protection_plan               0
premium_tech_support                 0
streaming_tv                         0
streaming_movies                     0
streaming_music                      0
unlimited_data                       0
contract                             0
paperless_billing                    0
payment_method                       0
monthly_charge                       0
total_charges                        0
total_refunds                        0
total_extra_data_charges             0
total_long_distance_charges          0
total_revenue                        0
satisfaction_score                   0
customer_status                      0
churn_label                          0
churn_score                          0
cltv                                 0
churn_category                       0
churn_reason                         0
dtype: int64

In [22]:
df[df["senior_citizen"] == "Yes"]["age"].describe()

count    1142.000000
mean       72.457093
std         4.583952
min        65.000000
25%        69.000000
50%        73.000000
75%        76.000000
max        80.000000
Name: age, dtype: float64

In [23]:
df[df["senior_citizen"] == "No"]["age"].describe()

count    2534.000000
mean       41.854380
std        13.253001
min        19.000000
25%        30.000000
50%        42.000000
75%        53.000000
max        64.000000
Name: age, dtype: float64

In [24]:
df[df["senior_citizen"] == "Yes"]["age"].min()

65

In [25]:
df[df["senior_citizen"] == "No"]["age"].max()

64

In [26]:
df[df["under_30"] == "No"]["age"].min()

30

In [29]:
df.loc[:,"age_group"] = pd.cut(
    df["age"],
    bins=[0, 29, 64, 100],
    labels=["Under 30", "Middle age", "Senior Citizen"]
)

In [32]:
print(df[["age","age_group"]])

      age       age_group
0      78  Senior Citizen
1      74  Senior Citizen
2      71  Senior Citizen
3      78  Senior Citizen
4      80  Senior Citizen
...   ...             ...
3671   51      Middle age
3672   32      Middle age
3673   37      Middle age
3674   54      Middle age
3675   36      Middle age

[3676 rows x 2 columns]

In [33]:
df = df.drop(columns = ["under_30", "senior_citizen"])

In [43]:
df = df.drop(columns = ["dependents", "referred_a_friend"])

In [44]:
df.shape

(3676, 44)

In [45]:
df.columns

Index(['customer_id', 'gender', 'age', 'married', 'number_of_dependents',
       'city', 'zip_code', 'latitude', 'longitude', 'population',
       'number_of_referrals', 'tenure_in_months', 'offer', 'phone_service',
       'avg_monthly_long_distance_charges', 'multiple_lines',
       'internet_service', 'internet_type', 'avg_monthly_gb_download',
       'online_security', 'online_backup', 'device_protection_plan',
       'premium_tech_support', 'streaming_tv', 'streaming_movies',
       'streaming_music', 'unlimited_data', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charge', 'total_charges', 'total_refunds',
       'total_extra_data_charges', 'total_long_distance_charges',
       'total_revenue', 'satisfaction_score', 'customer_status', 'churn_label',
       'churn_score', 'cltv', 'churn_category', 'churn_reason', 'age_group'],
      dtype='object')

In [46]:
df.head()

,customer_id,gender,age,married,number_of_dependents,city,zip_code,latitude,longitude,population,...,total_long_distance_charges,total_revenue,satisfaction_score,customer_status,churn_label,churn_score,cltv,churn_category,churn_reason,age_group
0,8779-QRDMV,Male,78,No,0,Los Angeles,90022,34.023810,-118.156582,68701,...,0.00,59.65,3.0,Churned,Yes,91.0,5433.0,Competitor,Competitor offered more data,Senior Citizen
1,7495-OOKFY,Female,74,Yes,1,Los Angeles,90063,34.044271,-118.185237,55668,...,390.80,1024.10,3.0,Churned,Yes,69.0,5302.0,Competitor,Competitor made better offer,Senior Citizen
2,1658-BYGOY,Male,71,No,3,Los Angeles,90065,34.108833,-118.229715,47534,...,203.94,1910.88,2.0,Churned,Yes,81.0,3179.0,Competitor,Competitor made better offer,Senior Citizen
3,4598-XLKNJ,Female,78,Yes,1,Inglewood,90303,33.936291,-118.332639,27778,...,494.00,2995.07,2.0,Churned,Yes,88.0,5337.0,Dissatisfaction,Limited range of services,Senior Citizen
4,4846-WHAFZ,Female,80,Yes,1,Whittier,90602,33.972119,-118.020188,26265,...,234.21,3102.36,2.0,Churned,Yes,67.0,2793.0,Price,Extra data charges,Senior Citizen

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3676 entries, 0 to 3675
Data columns (total 44 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   customer_id                        3676 non-null   object
 1   gender                             3676 non-null   object
 2   age                                3676 non-null   int64
 3   married                            3676 non-null   object
 4   number_of_dependents               3676 non-null   int64
 5   city                               3676 non-null   object
 6   zip_code                           3676 non-null   int64
 7   latitude                           3676 non-null   float64
 8   longitude                          3676 non-null   float64
 9   population                         3676 non-null   int64
 10  number_of_referrals                3676 non-null   int64
 11  tenure_in_months                   3676 non-null   int64
 12  offer                              3676 non-null   object
 13  phone_service                      3676 non-null   object
 14  avg_monthly_long_distance_charges  3676 non-null   float64
 15  multiple_lines                     3676 non-null   object
 16  internet_service                   3676 non-null   object
 17  internet_type                      3676 non-null   object
 18  avg_monthly_gb_download            3676 non-null   int64
 19  online_security                    3676 non-null   object
 20  online_backup                      3676 non-null   object
 21  device_protection_plan             3676 non-null   object
 22  premium_tech_support               3676 non-null   object
 23  streaming_tv                       3676 non-null   object
 24  streaming_movies                   3676 non-null   object
 25  streaming_music                    3676 non-null   object
 26  unlimited_data                     3676 non-null   object
 27  contract                           3676 non-null   object
 28  paperless_billing                  3676 non-null   object
 29  payment_method                     3676 non-null   object
 30  monthly_charge                     3676 non-null   float64
 31  total_charges                      3676 non-null   float64
 32  total_refunds                      3676 non-null   float64
 33  total_extra_data_charges           3676 non-null   float64
 34  total_long_distance_charges        3676 non-null   float64
 35  total_revenue                      3676 non-null   float64
 36  satisfaction_score                 3676 non-null   float64
 37  customer_status                    3676 non-null   object
 38  churn_label                        3676 non-null   object
 39  churn_score                        3676 non-null   float64
 40  cltv                               3676 non-null   float64
 41  churn_category                     3676 non-null   object
 42  churn_reason                       3676 non-null   object
 43  age_group                          3676 non-null   category
dtypes: category(1), float64(12), int64(7), object(24)
memory usage: 1.2+ MB

In [48]:
df.isnull().sum()

customer_id                          0
gender                               0
age                                  0
married                              0
number_of_dependents                 0
city                                 0
zip_code                             0
latitude                             0
longitude                            0
population                           0
number_of_referrals                  0
tenure_in_months                     0
offer                                0
phone_service                        0
avg_monthly_long_distance_charges    0
multiple_lines                       0
internet_service                     0
internet_type                        0
avg_monthly_gb_download              0
online_security                      0
online_backup                        0
device_protection_plan               0
premium_tech_support                 0
streaming_tv                         0
streaming_movies                     0
streaming_music                      0
unlimited_data                       0
contract                             0
paperless_billing                    0
payment_method                       0
monthly_charge                       0
total_charges                        0
total_refunds                        0
total_extra_data_charges             0
total_long_distance_charges          0
total_revenue                        0
satisfaction_score                   0
customer_status                      0
churn_label                          0
churn_score                          0
cltv                                 0
churn_category                       0
churn_reason                         0
age_group                            0
dtype: int64

In [70]:
df.to_csv("Cleaned_telco_churn.csv", index = False)